# Buildspec Reference Doc: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

version: 0.2

phases:
  install:
    commands:
      - echo "[+] Scanning for security vulnerability within dependencies"
      # - pipenv check (if pipenv is installed and a Pipfile is in place)
      # - Alternatively: https://www.owasp.org/index.php/OWASP_Dependency_Check
  pre_build:
    commands:
      - echo "[+] Installing dependencies...."
      # - pip install -r <src>/requirements.txt -t <src>/dev/
      - echo "[+] Running tests..."
      # - python -m pytest tests/
      - echo "Prepackaging... copying functions to dev directories"
      - cp steps/adminAction/lambda_function.py steps/adminAction/dev/lambda_function.py
      - cp steps/registerIncident/lambda_function.py steps/registerIncident/dev/lambda_function.py
      - cp steps/resolveIncident/lambda_function.py steps/resolveIncident/dev/lambda_function.py
      - cp steps/sendNotification/lambda_function.py steps/sendNotification/dev/lambda_function.py
      - cp steps/validateExam/lambda_function.py steps/validateExam/dev/lambda_function.py
  build:
    commands:
      - echo "Starting SAM packaging `date` in `pwd`"
      - cd steps && aws cloudformation package --template-file template.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file packaged.yaml
  post_build:
    commands:
      - echo "SAM packaging completed on `date`"

artifacts:
  files:
    - steps/packaged.yaml
  discard-paths: yes

cache:
  paths:
    - '/root/.cache/pip'
